/* Replace with your SQL commands */
begin;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create schema if not exists product;

create table if not exists product.products (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null default uuid_generate_v4(),

    name varchar(255) not null,
    sku varchar(255),
    shop_id varchar(255) not null,
    description text not null,
    active boolean not null,
    brand varchar(255),
    category varchar(255),
    images jsonb,
    video varchar(255),
    status varchar(255) not null
);

create table if not exists product.variants (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null default uuid_generate_v4(),

    product_id uuid not null,
    name varchar(255) not null,
    sku varchar(255),
    variant_type varchar(255) not null,
    price float not null,
    active boolean not null,
    stock integer not null,
    image varchar(255),
    weight float not null,
    length float not null,
    width float not null,
    height float not null
);

commit;